apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/target: "10"
  name: mistral-7b-instruct-v03-1xgpu
spec:
  predictor:
    minReplicas: 1
    model:
      modelFormat:
        name: nvidia-nim-mistral-7b-instruct-v03
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      runtime: nvidia-nim-mistral-7b-instruct-v03-1.0.0
      storageUri: oci://quay.io/xiezhang7/mistral-7b-instruct-v03:v1.0.0-cache
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: odh-notebook
        operator: Exists
    nodeSelector:
      node.kubernetes.io/instance-type: p4d.24xlarge
